/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as IndexRouteImport } from './routes/index'

const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/concepts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/concepts'
  id: '__root__' | '/' | '/concepts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsRoute: typeof ConceptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsRoute: ConceptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
