/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPricesRouteImport } from './routes/api/prices'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/prices': typeof PricesRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/prices': typeof ApiPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/prices': typeof PricesRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/prices': typeof ApiPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/prices': typeof PricesRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/prices': typeof ApiPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concepts'
    | '/prices'
    | '/simulator'
    | '/sitemap.xml'
    | '/api/prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concepts'
    | '/prices'
    | '/simulator'
    | '/sitemap.xml'
    | '/api/prices'
  id:
    | '__root__'
    | '/'
    | '/concepts'
    | '/prices'
    | '/simulator'
    | '/sitemap.xml'
    | '/api/prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsRoute: typeof ConceptsRoute
  PricesRoute: typeof PricesRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPricesRoute: typeof ApiPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsRoute: ConceptsRoute,
  PricesRoute: PricesRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPricesRoute: ApiPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
